version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    groups:
      typescript-eslint-deps:
        patterns:
          - 'typescript-eslint'
          - '@typescript-eslint*'
      eslint-desp:
        patterns:
          - '@eslint*'
          - 'eslint*'
      commitlint-deps:
        patterns:
          - '@commitlint*'
